import jsPDF from "jspdf";

function ExportAIReport({ report }) {
  const exportPDF = () => {
    const doc = new jsPDF();

    let y = 20;

    doc.setFontSize(22);
    doc.text("MedAssist AI", 20, y);

    y += 10;

    doc.setFontSize(16);
    doc.text("AI Medical Report", 20, y);

    y += 15;

    doc.setFontSize(12);

    doc.text(`File: ${report.filename}`, 20, y);
    y += 8;

    doc.text(
      `Health Score: ${report.aiAnalysis?.healthScore}/100`,
      20,
      y
    );
    y += 8;

    doc.text(
      `Risk Level: ${report.aiAnalysis?.riskLevel}`,
      20,
      y
    );

    y += 15;

    doc.setFontSize(14);
    doc.text("Health Summary", 20, y);

    y += 10;

    const summary = report.aiAnalysis?.summary || {};

    Object.entries(summary).forEach(([key, value]) => {
      doc.setFontSize(11);

      doc.text(
        `${key}: ${value?.value || "N/A"} (${value?.status || ""})`,
        20,
        y
      );

      y += 8;
    });

    y += 8;

    doc.setFontSize(14);
    doc.text("Recommendations", 20, y);

    y += 10;

    report.aiAnalysis?.recommendations?.forEach((item) => {
      doc.setFontSize(11);

      doc.text(
        `• ${typeof item === "object" ? item.advice : item}`,
        25,
        y
      );

      y += 8;
    });

    y += 8;

    doc.setFontSize(14);
    doc.text("Lifestyle Advice", 20, y);

    y += 10;

    report.aiAnalysis?.lifestyleAdvice?.forEach((item) => {
      doc.setFontSize(11);

      doc.text(
        `• ${typeof item === "object" ? item.advice : item}`,
        25,
        y
      );

      y += 8;
    });

    y += 8;

    doc.setFontSize(14);
    doc.text("Possible Diseases", 20, y);

    y += 10;

    report.aiAnalysis?.possibleDiseases?.forEach((item) => {
      doc.setFontSize(11);

      doc.text(
        `• ${typeof item === "object" ? item.name : item}`,
        25,
        y
      );

      y += 8;
    });

    y += 8;

    doc.setFontSize(10);

    doc.text(
      report.aiAnalysis?.disclaimer ||
        "Generated by MedAssist AI",
      20,
      y
    );

    doc.save("AI_Medical_Report.pdf");
  };

  return (
    <button
      onClick={exportPDF}
      className="rounded-xl bg-cyan-600 px-5 py-2 font-semibold hover:bg-cyan-700"
    >
      📄 Export AI PDF
    </button>
  );
}

export default ExportAIReport;